[project]
site_name = "KMP Starter Docs"
site_description = "Documentation for KMP Starter Template"
site_url="https://devatrii.github.io/Kmp-Starter-Template"
repo_name = "devatrii/kmp-starter-template"
repo_url="https://github.com/DevAtrii/Kmp-Starter-Template"
nav = [
  {"Home" = "index.md"},
  {"Getting Started" = "getting-started.md"},
  {"Customization" = [
    "customization/0-metadata.md",
    "customization/1-theme.md",
  ]},
  {"Fundamentals" = [
    "fundamentals/00-architecture.md",
    "fundamentals/01-kmp-app.md",
    "fundamentals/02-dependency-injection.md",
    "fundamentals/03-platform-class.md",
    "fundamentals/04-native-bindings.md",
    "fundamentals/05-datastores.md",
    "fundamentals/06-resources.md",
    "fundamentals/07-multiple-languages.md",
    "fundamentals/08-navigation.md",
    "fundamentals/09-store-reviews-and-updates.md",
    "fundamentals/10-logging.md",
    "fundamentals/11-swift-package-manager.md",
    "fundamentals/12-writing-your-code.md",
  ]},
  {"Features" = [
     "features/0-core.md",
     "features/1-remote-config.md",
     "features/2-analytics.md",
     "features/3-database.md",
     "features/4-purchases.md"
  ]}
]


[project.theme]
name = "KMP Starter Docs"
logo = "assets/logo.webp"
favicon = "assets/favicon/favicon.ico"
custom_dir = "docs/overrides"
features = [
    "navigation.footer",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.path",
    "navigation.top",
    "search.suggest",
    "search.highlight",
    "content.code.copy",
    "content.code.annotate",
    "content.code.select",
    "content.tooltips"
]

[[project.theme.palette]]
scheme = "slate"
primary = "green"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "green"
accent = "green"




[project.extra.analytics.feedback]
title = "Was this page helpful?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "This page was helpful"
data = 1
note = "Thanks for your feedback!"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "This page could be improved"
data = 0
note = """
  Thanks for your feedback! Help us improve this page by
  using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
"""


[markdown_extensions]
admonition = {}
footnotes = {}
def_list = {}
"pymdownx.details" = {}
"pymdownx.superfences" = {}
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
copy_button = {}
attr_list = {}
md_in_html = {}

# socials
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/DevAtrii/Kmp-Starter-Template"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/dev_atrii"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://youtube.com/@devatrii"