[project]
site_name = "KMP Starter Docs"
site_description = "Documentation for KMP Starter Template"
site_url="https://devatrii.github.io/Kmp-Starter-Template"
repo_name = "devatrii/kmp-starter-template"
repo_url="https://github.com/DevAtrii/Kmp-Starter-Template"



[project.theme]
name = "KMP Starter Docs"
logo = "assets/logo.webp"
favicon = "assets/favicon/favicon.ico"
custom_dir = "docs/overrides"
features = [
    "navigation.footer",
    "navigation.tabs",
    "navigation.tabs.sticky",
    "navigation.instant",
    "navigation.instant.prefetch",
    "navigation.instant.progress",
    "navigation.path",
    "navigation.top",
    "search.suggest",
    "search.highlight",
    "content.code.copy",
    "content.code.annotate",
    "content.code.select",
    "content.tooltips"
]



[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"
primary = "green"
accent = "green"

[[project.theme.palette]]
scheme = "slate"
primary = "green"
accent = "green"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"
font.text="cursive"
font.code="Google Sans Code"


[project.extra.analytics.feedback]
title = "Was this page helpful?"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-happy-outline"
name = "This page was helpful"
data = 1
note = "Thanks for your feedback!"

[[project.extra.analytics.feedback.ratings]]
icon = "material/emoticon-sad-outline"
name = "This page could be improved"
data = 0
note = """
  Thanks for your feedback! Help us improve this page by
  using our <a href="..." target="_blank" rel="noopener">feedback form</a>.
"""


[markdown_extensions]
admonition = {}
footnotes = {}
def_list = {}
"pymdownx.details" = {}
"pymdownx.superfences" = {}
"pymdownx.inlinehilite" = {}
"pymdownx.snippets" = {}
copy_button = {}
attr_list = {}
md_in_html = {}

# socials
[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/DevAtrii/Kmp-Starter-Template"

[[project.extra.social]]
icon = "fontawesome/brands/x-twitter"
link = "https://x.com/dev_atrii"

[[project.extra.social]]
icon = "fontawesome/brands/youtube"
link = "https://youtube.com/@devatrii"